# Generated by Django 5.1.4 on 2025-05-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karzina_tovar',
            name='kolvo',
            field=models.IntegerField(default=1),
        ),
    ]
